image: node:8.9

# https://community.atlassian.com/t5/Bitbucket-questions/Is-Yarn-supported-for-bitbucket-pipelines-caching/qaq-p/650816

pipelines:
  default:
    - step:
        caches:
          - yarncustom
        script: 
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn global add lerna
          - lerna bootstrap
          # - yarn test
          - yarn build
definitions:
  caches:
    yarncustom: /usr/local/share/.cache/yarn/v1
