image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: 
          - curl -o- -L https://yarnpkg.com/install.sh | bash
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn test
